title: k7t3 repositories
description: repositories
remote_theme: pages-themes/cayman@v0.2.0
google_analytics: G-645SD0FB9D
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
google_search_console:
  verification_file_code: ab828e8d00b0f375