title: k7t3 repositories

exclude: [.gitignore, Dockerfile, docker, Gemfile, Gemfile.lock, README.md]

remote_theme: pages-themes/cayman@v0.2.0

google_analytics: G-645SD0FB9D

google_search_console:
  verification_file_code: ab828e8d00b0f375

plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-favicon
  - jekyll-github-metadata

favicon:
  source: res/icon.png

lang: ja-JP

github:
  is_project_page: false